name: Extract Docker Image

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull labani/stream:latest

      - name: Create and export container
        run: |
          docker create --name tempcontainer labani/stream:latest
          docker export tempcontainer > stream.tar
          mkdir extracted
          tar -xf stream.tar -C extracted
          ls extracted > extracted/listing.txt

      - name: Upload extracted files
        uses: actions/upload-artifact@v4
        with:
          name: extracted-stream
          path: extracted/
